#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER1='/home/hankp/Pictures/wallpapers/astronaut.png'
WALLPAPER2='/home/hankp/Pictures/wallpapers/arch_wallpaper.png'

swaybg --output 'DP-2' --mode fill --image "$WALLPAPER1" --output 'HDMI-A-1' --mode fill --image "$WALLPAPER2"
